import '../styles/globals.css';

import ScreenLayout from '@/layout/screen/ScreenLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className="bg-bgDefault pt-85">
        <ScreenLayout>{children}</ScreenLayout>
      </body>
    </html>
  );
};

export default RootLayout;
