import '../styles/globals.css';

import ScreenLayout from '@/layout/screen/ScreenLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-bgDefault">
        <ScreenLayout>{children}</ScreenLayout>
      </body>
    </html>
  );
}
