import '../styles/globals.css';

import { cookies } from 'next/headers';

import ScreenLayout from '@/layout/screen/ScreenLayout';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const apiKey = cookies().get('key');

  return (
    <html lang="en">
      <body className="bg-bgDefault pt-85">
        <ScreenLayout apiKey={apiKey}>{children}</ScreenLayout>
      </body>
    </html>
  );
};

export default RootLayout;
